name: AdvancedRename
version: 1.0.0
author: FlareReturns
main: ch.FlareReturns.AdvancedRename.KingRenameMain
commands:
  glow:
    aliases: [gloweffect]
  relore:
    aliases: [rl]
  rename:
    aliases: [rn]
  resetglow:
    aliases: [rg, removeglow]